package bank_sys;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.Date;
import java.util.Scanner;
public class transfer extends javax.swing.JFrame {
    Connection con;
    int u_id;
    int t_id;
    double amount,balance;
    public transfer(int cl_id) {
        this.u_id=cl_id;
        initComponents();
        this.setLocationRelativeTo(null);
        try {
             con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bank2", "root", "root");
             PreparedStatement stmt=con.prepareStatement("select * from client");
            ResultSet res= stmt.executeQuery();
           
            while(res.next())
            {
                if(u_id==res.getInt(1))
                {
                    double bal=res.getDouble(4);
                    balance=bal;
                    tf_balance.setText(""+bal);
                }
            }
        } catch (SQLException ex) {
             Logger.getLogger(addclient.class.getName()).log(Level.SEVERE, null, ex);    
        }
    }

    public transfer() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_amount = new javax.swing.JLabel();
        tf_balance = new javax.swing.JTextField();
        lbl_transfer = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        btn_back = new javax.swing.JButton();
        btn_submit = new javax.swing.JButton();
        lbl_balance1 = new javax.swing.JLabel();
        tf_amount = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        lbl_amount.setFont(new java.awt.Font("Segoe UI Black", 3, 20)); // NOI18N
        lbl_amount.setForeground(new java.awt.Color(255, 255, 255));
        lbl_amount.setText("amount of money");

        tf_balance.setEditable(false);
        tf_balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_balanceActionPerformed(evt);
            }
        });

        lbl_transfer.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        lbl_transfer.setForeground(new java.awt.Color(255, 255, 255));
        lbl_transfer.setText("Transfer");

        lbl_id.setFont(new java.awt.Font("Segoe UI Black", 3, 20)); // NOI18N
        lbl_id.setForeground(new java.awt.Color(255, 255, 255));
        lbl_id.setText("ID of the client to transfer money");

        tf_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idActionPerformed(evt);
            }
        });

        btn_back.setBackground(new java.awt.Color(0, 102, 102));
        btn_back.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        btn_submit.setBackground(new java.awt.Color(0, 102, 102));
        btn_submit.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        lbl_balance1.setFont(new java.awt.Font("Segoe UI Black", 3, 20)); // NOI18N
        lbl_balance1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_balance1.setText("Your balance:");

        tf_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_amountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(lbl_transfer))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addComponent(btn_submit)
                            .addGap(123, 123, 123)
                            .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbl_amount)
                                    .addGap(18, 18, 18)
                                    .addComponent(tf_amount))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbl_id)
                                    .addGap(24, 24, 24)
                                    .addComponent(tf_id))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbl_balance1)
                                    .addGap(18, 18, 18)
                                    .addComponent(tf_balance, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbl_transfer)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_balance, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_balance1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(tf_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_back)
                    .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_balanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_balanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_balanceActionPerformed

    private void tf_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_idActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        new cl_options(u_id).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
        
        if(!tf_id.getText().isEmpty()&&!tf_amount.getText().isEmpty())
        {   
            if(is_valid_number(tf_amount.getText())&&is_valid_int(tf_id.getText()))
            {
                t_id=Integer.parseInt(tf_id.getText());
            
                amount= Double.parseDouble(tf_amount.getText());
                try {
                boolean f=false;
                PreparedStatement stmt=con.prepareStatement("select *from client");
                ResultSet res=stmt.executeQuery();
                while(res.next())
                {
                    if(t_id==res.getInt(1))
                    {
                        f=true;
                        break;
                    }
                }
                if(t_id!=u_id)
                {if(f)
                {
                   
                    if(amount<=balance)
                    {
                        double user_result =balance-amount;
                        PreparedStatement userupdate=con.prepareStatement("update client set balance=? where cl_id=?");
                        userupdate.setInt(2,u_id);
                        userupdate.setDouble(1, user_result);
                        userupdate.executeUpdate();
                        PreparedStatement clientupdate=con.prepareStatement("update client set balance=? where cl_id=?");
                        tf_balance.setText(""+user_result);
                        clientupdate.setDouble(1, amount+res.getDouble(4));
                        clientupdate.setInt(2, t_id);
                        clientupdate.executeUpdate();
                        PreparedStatement st=con.prepareStatement("insert into transfer (id_transferto,amount,cl_id ,trans_date) values(?,?,?,?)");
                        st.setInt(1,t_id);
                        st.setDouble(2, amount);
                        st.setInt(3, u_id);
                        Date d=new Date();
                        SimpleDateFormat s=new SimpleDateFormat("dd/MM/yyyy | hh:mm:ss");
                        st.setString(4,String.valueOf(s.format(d)) );
                        st.execute();
                        JOptionPane.showMessageDialog(null, "operation successed");
                        tf_id.setText("");
                        tf_amount.setText("");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "not enough money in the balance");
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "this client doesn't exist");
                    
                }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "you can't transfer money to yourself");
                }
            } catch (SQLException ex) {
                Logger.getLogger(wi_de.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "please enter valid numbers");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "you must fill all the cells");
        }
    }//GEN-LAST:event_btn_submitActionPerformed
    public boolean is_valid_number(String s)
    {
        try {
         
         Double doub = Double.parseDouble(s);
         
      }
        catch (NumberFormatException ex) {
         return false;
      }
        return true;
    }
    public boolean is_valid_int(String s)
    {
        for(int i=0;i<s.length();i++)
        {
            if(!Character.isDigit(s.charAt(i)))
                return false;
        }
        return true;
    }
        
    private void tf_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_amountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_submit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_amount;
    private javax.swing.JLabel lbl_balance1;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_transfer;
    private javax.swing.JTextField tf_amount;
    private javax.swing.JTextField tf_balance;
    private javax.swing.JTextField tf_id;
    // End of variables declaration//GEN-END:variables
}
